### ISSUE TITLE
Nice job

### ISSUE THREAD

**Issue by spcrxj** [andre-zh/django_yolov5#1]
May I ash what are you doing this for? Many thanks. Have a good day sir.

**Comment by andre-zh** [comment]
Thanks for your question.
Basically, this is a deployment of yolov5 as a web service by using Django. This is only for test purpose so please dont use it in real industry implementation. Better ways of doing this could be using Triton and tensorRT.

**Comment by andre-zh** [comment]
Thanks for the question.
Basically, this is a deployment of yolov5 as a web service by using Django. This is only for test purpose so please dont use it in real industry implementation. Better ways of doing this could be using Triton and tensorRT.

**Comment by andre-zh** [comment]
Yidegelami
